using Microsoft.EntityFrameworkCore;
using Sseko.Data.Models;

namespace Sseko.Data
{
    public partial class SsekoContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            #warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
            optionsBuilder.UseMySql(@"Server=rds-slave-2-sseko.czts6uwbwov0.us-west-2.rds.amazonaws.com; Port=3306; Database=magento; Uid=magento; Pwd=qBNkM486X6nyhGwREv; SslMode=Preferred;");
            //optionsBuilder.UseMySql(@"Server=localhost; Port=3306; Database=sseko; Uid=root; Pwd=Kazam2359; SslMode=Preferred;");
        }

#region DbSets
        public virtual DbSet<AdminAssert> AdminAssert { get; set; }
        public virtual DbSet<AdminnotificationInbox> AdminnotificationInbox { get; set; }
        public virtual DbSet<AdminRole> AdminRole { get; set; }
        public virtual DbSet<AdminRule> AdminRule { get; set; }
        public virtual DbSet<AdminUser> AdminUser { get; set; }
        public virtual DbSet<AffiliateplusAccount> AffiliateplusAccount { get; set; }
        public virtual DbSet<AffiliateplusAccountValue> AffiliateplusAccountValue { get; set; }
        public virtual DbSet<AffiliateplusAction> AffiliateplusAction { get; set; }
        public virtual DbSet<AffiliateplusBanner> AffiliateplusBanner { get; set; }
        public virtual DbSet<AffiliateplusBannerValue> AffiliateplusBannerValue { get; set; }
        public virtual DbSet<AffiliateplusCoupon> AffiliateplusCoupon { get; set; }
        public virtual DbSet<AffiliateplusCredit> AffiliateplusCredit { get; set; }
        public virtual DbSet<AffiliatepluslevelTier> AffiliatepluslevelTier { get; set; }
        public virtual DbSet<AffiliatepluslevelTransaction> AffiliatepluslevelTransaction { get; set; }
        public virtual DbSet<AffiliateplusPayment> AffiliateplusPayment { get; set; }
        public virtual DbSet<AffiliatepluspaymentBank> AffiliatepluspaymentBank { get; set; }
        public virtual DbSet<AffiliatepluspaymentBankaccount> AffiliatepluspaymentBankaccount { get; set; }
        public virtual DbSet<AffiliateplusPaymentHistory> AffiliateplusPaymentHistory { get; set; }
        public virtual DbSet<AffiliatepluspaymentMoneybooker> AffiliatepluspaymentMoneybooker { get; set; }
        public virtual DbSet<AffiliatepluspaymentOffline> AffiliatepluspaymentOffline { get; set; }
        public virtual DbSet<AffiliateplusPaymentPaypal> AffiliateplusPaymentPaypal { get; set; }
        public virtual DbSet<AffiliateplusPaymentVerify> AffiliateplusPaymentVerify { get; set; }
        public virtual DbSet<Affiliateplusprogram> Affiliateplusprogram { get; set; }
        public virtual DbSet<AffiliateplusprogramAccount> AffiliateplusprogramAccount { get; set; }
        public virtual DbSet<AffiliateplusprogramCategory> AffiliateplusprogramCategory { get; set; }
        public virtual DbSet<AffiliateplusprogramJoined> AffiliateplusprogramJoined { get; set; }
        public virtual DbSet<AffiliateplusprogramProduct> AffiliateplusprogramProduct { get; set; }
        public virtual DbSet<AffiliateplusprogramTransaction> AffiliateplusprogramTransaction { get; set; }
        public virtual DbSet<AffiliateplusprogramValue> AffiliateplusprogramValue { get; set; }
        public virtual DbSet<AffiliateplusReferer> AffiliateplusReferer { get; set; }
        public virtual DbSet<Affiliateplusstatistic> Affiliateplusstatistic { get; set; }
        public virtual DbSet<AffiliateplusTracking> AffiliateplusTracking { get; set; }
        public virtual DbSet<AffiliateplusTransaction> AffiliateplusTransaction { get; set; }
        public virtual DbSet<Api2AclAttribute> Api2AclAttribute { get; set; }
        public virtual DbSet<Api2AclRole> Api2AclRole { get; set; }
        public virtual DbSet<Api2AclRule> Api2AclRule { get; set; }
        public virtual DbSet<Api2AclUser> Api2AclUser { get; set; }
        public virtual DbSet<ApiAssert> ApiAssert { get; set; }
        public virtual DbSet<ApiRole> ApiRole { get; set; }
        public virtual DbSet<ApiRule> ApiRule { get; set; }
        public virtual DbSet<ApiUser> ApiUser { get; set; }
        public virtual DbSet<ApptrianImageoptimizerFiles> ApptrianImageoptimizerFiles { get; set; }
        public virtual DbSet<CaptchaLog> CaptchaLog { get; set; }
        public virtual DbSet<CatalogCategoryEntity> CatalogCategoryEntity { get; set; }
        public virtual DbSet<CatalogCategoryEntityDatetime> CatalogCategoryEntityDatetime { get; set; }
        public virtual DbSet<CatalogCategoryEntityDecimal> CatalogCategoryEntityDecimal { get; set; }
        public virtual DbSet<CatalogCategoryEntityInt> CatalogCategoryEntityInt { get; set; }
        public virtual DbSet<CatalogCategoryEntityText> CatalogCategoryEntityText { get; set; }
        public virtual DbSet<CatalogCategoryEntityVarchar> CatalogCategoryEntityVarchar { get; set; }
        public virtual DbSet<CatalogCategoryFlatStore1> CatalogCategoryFlatStore1 { get; set; }
        public virtual DbSet<CatalogCategoryFlatStore2> CatalogCategoryFlatStore2 { get; set; }
        public virtual DbSet<CatalogCategoryFlatStore3> CatalogCategoryFlatStore3 { get; set; }
        public virtual DbSet<CatalogCategoryProduct> CatalogCategoryProduct { get; set; }
        public virtual DbSet<CatalogCategoryProductIndex> CatalogCategoryProductIndex { get; set; }
        public virtual DbSet<CatalogCompareItem> CatalogCompareItem { get; set; }
        public virtual DbSet<CatalogEavAttribute> CatalogEavAttribute { get; set; }
        public virtual DbSet<CataloginventoryStock> CataloginventoryStock { get; set; }
        public virtual DbSet<CataloginventoryStockItem> CataloginventoryStockItem { get; set; }
        public virtual DbSet<CataloginventoryStockStatus> CataloginventoryStockStatus { get; set; }
        public virtual DbSet<CataloginventoryStockStatusIdx> CataloginventoryStockStatusIdx { get; set; }
        public virtual DbSet<CataloginventoryStockStatusTmp> CataloginventoryStockStatusTmp { get; set; }
        public virtual DbSet<CatalogProductBundleOption> CatalogProductBundleOption { get; set; }
        public virtual DbSet<CatalogProductBundleOptionValue> CatalogProductBundleOptionValue { get; set; }
        public virtual DbSet<CatalogProductBundlePriceIndex> CatalogProductBundlePriceIndex { get; set; }
        public virtual DbSet<CatalogProductBundleSelection> CatalogProductBundleSelection { get; set; }
        public virtual DbSet<CatalogProductBundleSelectionPrice> CatalogProductBundleSelectionPrice { get; set; }
        public virtual DbSet<CatalogProductBundleStockIndex> CatalogProductBundleStockIndex { get; set; }
        public virtual DbSet<CatalogProductEnabledIndex> CatalogProductEnabledIndex { get; set; }
        public virtual DbSet<CatalogProductEntity> CatalogProductEntity { get; set; }
        public virtual DbSet<CatalogProductEntityDatetime> CatalogProductEntityDatetime { get; set; }
        public virtual DbSet<CatalogProductEntityDecimal> CatalogProductEntityDecimal { get; set; }
        public virtual DbSet<CatalogProductEntityGallery> CatalogProductEntityGallery { get; set; }
        public virtual DbSet<CatalogProductEntityGroupPrice> CatalogProductEntityGroupPrice { get; set; }
        public virtual DbSet<CatalogProductEntityInt> CatalogProductEntityInt { get; set; }
        public virtual DbSet<CatalogProductEntityMediaGallery> CatalogProductEntityMediaGallery { get; set; }
        public virtual DbSet<CatalogProductEntityMediaGalleryValue> CatalogProductEntityMediaGalleryValue { get; set; }
        public virtual DbSet<CatalogProductEntityText> CatalogProductEntityText { get; set; }
        public virtual DbSet<CatalogProductEntityTierPrice> CatalogProductEntityTierPrice { get; set; }
        public virtual DbSet<CatalogProductEntityVarchar> CatalogProductEntityVarchar { get; set; }
        public virtual DbSet<CatalogProductFlat1> CatalogProductFlat1 { get; set; }
        public virtual DbSet<CatalogProductFlat2> CatalogProductFlat2 { get; set; }
        public virtual DbSet<CatalogProductFlat3> CatalogProductFlat3 { get; set; }
        public virtual DbSet<CatalogProductIndexEav> CatalogProductIndexEav { get; set; }
        public virtual DbSet<CatalogProductIndexEavDecimal> CatalogProductIndexEavDecimal { get; set; }
        public virtual DbSet<CatalogProductIndexEavDecimalIdx> CatalogProductIndexEavDecimalIdx { get; set; }
        public virtual DbSet<CatalogProductIndexEavDecimalTmp> CatalogProductIndexEavDecimalTmp { get; set; }
        public virtual DbSet<CatalogProductIndexEavIdx> CatalogProductIndexEavIdx { get; set; }
        public virtual DbSet<CatalogProductIndexEavTmp> CatalogProductIndexEavTmp { get; set; }
        public virtual DbSet<CatalogProductIndexGroupPrice> CatalogProductIndexGroupPrice { get; set; }
        public virtual DbSet<CatalogProductIndexPrice> CatalogProductIndexPrice { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleIdx> CatalogProductIndexPriceBundleIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleOptIdx> CatalogProductIndexPriceBundleOptIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleOptTmp> CatalogProductIndexPriceBundleOptTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleSelIdx> CatalogProductIndexPriceBundleSelIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleSelTmp> CatalogProductIndexPriceBundleSelTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceBundleTmp> CatalogProductIndexPriceBundleTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceCfgOptAgrIdx> CatalogProductIndexPriceCfgOptAgrIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceCfgOptAgrTmp> CatalogProductIndexPriceCfgOptAgrTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceCfgOptIdx> CatalogProductIndexPriceCfgOptIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceCfgOptTmp> CatalogProductIndexPriceCfgOptTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceDownlodIdx> CatalogProductIndexPriceDownlodIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceDownlodTmp> CatalogProductIndexPriceDownlodTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceFinalIdx> CatalogProductIndexPriceFinalIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceFinalTmp> CatalogProductIndexPriceFinalTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceIdx> CatalogProductIndexPriceIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceOptAgrIdx> CatalogProductIndexPriceOptAgrIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceOptAgrTmp> CatalogProductIndexPriceOptAgrTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceOptIdx> CatalogProductIndexPriceOptIdx { get; set; }
        public virtual DbSet<CatalogProductIndexPriceOptTmp> CatalogProductIndexPriceOptTmp { get; set; }
        public virtual DbSet<CatalogProductIndexPriceTmp> CatalogProductIndexPriceTmp { get; set; }
        public virtual DbSet<CatalogProductIndexTierPrice> CatalogProductIndexTierPrice { get; set; }
        public virtual DbSet<CatalogProductIndexWebsite> CatalogProductIndexWebsite { get; set; }
        public virtual DbSet<CatalogProductLink> CatalogProductLink { get; set; }
        public virtual DbSet<CatalogProductLinkAttribute> CatalogProductLinkAttribute { get; set; }
        public virtual DbSet<CatalogProductLinkAttributeDecimal> CatalogProductLinkAttributeDecimal { get; set; }
        public virtual DbSet<CatalogProductLinkAttributeInt> CatalogProductLinkAttributeInt { get; set; }
        public virtual DbSet<CatalogProductLinkAttributeVarchar> CatalogProductLinkAttributeVarchar { get; set; }
        public virtual DbSet<CatalogProductLinkType> CatalogProductLinkType { get; set; }
        public virtual DbSet<CatalogProductOption> CatalogProductOption { get; set; }
        public virtual DbSet<CatalogProductOptionPrice> CatalogProductOptionPrice { get; set; }
        public virtual DbSet<CatalogProductOptionTitle> CatalogProductOptionTitle { get; set; }
        public virtual DbSet<CatalogProductOptionTypePrice> CatalogProductOptionTypePrice { get; set; }
        public virtual DbSet<CatalogProductOptionTypeTitle> CatalogProductOptionTypeTitle { get; set; }
        public virtual DbSet<CatalogProductOptionTypeValue> CatalogProductOptionTypeValue { get; set; }
        public virtual DbSet<CatalogProductRelation> CatalogProductRelation { get; set; }
        public virtual DbSet<CatalogProductSuperAttribute> CatalogProductSuperAttribute { get; set; }
        public virtual DbSet<CatalogProductSuperAttributeLabel> CatalogProductSuperAttributeLabel { get; set; }
        public virtual DbSet<CatalogProductSuperAttributePricing> CatalogProductSuperAttributePricing { get; set; }
        public virtual DbSet<CatalogProductSuperLink> CatalogProductSuperLink { get; set; }
        public virtual DbSet<CatalogProductWebsite> CatalogProductWebsite { get; set; }
        public virtual DbSet<Catalogrule> Catalogrule { get; set; }
        public virtual DbSet<CatalogruleAffectedProduct> CatalogruleAffectedProduct { get; set; }
        public virtual DbSet<CatalogruleCustomerGroup> CatalogruleCustomerGroup { get; set; }
        public virtual DbSet<CatalogruleGroupWebsite> CatalogruleGroupWebsite { get; set; }
        public virtual DbSet<CatalogruleProduct> CatalogruleProduct { get; set; }
        public virtual DbSet<CatalogruleProductPrice> CatalogruleProductPrice { get; set; }
        public virtual DbSet<CatalogruleWebsite> CatalogruleWebsite { get; set; }
        public virtual DbSet<CatalogsearchFulltext> CatalogsearchFulltext { get; set; }
        public virtual DbSet<CatalogsearchQuery> CatalogsearchQuery { get; set; }
        public virtual DbSet<CatalogsearchResult> CatalogsearchResult { get; set; }
        public virtual DbSet<CheckoutAgreement> CheckoutAgreement { get; set; }
        public virtual DbSet<CheckoutAgreementStore> CheckoutAgreementStore { get; set; }
        public virtual DbSet<CmsBlock> CmsBlock { get; set; }
        public virtual DbSet<CmsBlockStore> CmsBlockStore { get; set; }
        public virtual DbSet<CmsPage> CmsPage { get; set; }
        public virtual DbSet<CmsPageStore> CmsPageStore { get; set; }
        public virtual DbSet<CoreCache> CoreCache { get; set; }
        public virtual DbSet<CoreCacheOption> CoreCacheOption { get; set; }
        public virtual DbSet<CoreCacheTag> CoreCacheTag { get; set; }
        public virtual DbSet<CoreConfigData> CoreConfigData { get; set; }
        public virtual DbSet<CoreEmailQueue> CoreEmailQueue { get; set; }
        public virtual DbSet<CoreEmailQueueRecipients> CoreEmailQueueRecipients { get; set; }
        public virtual DbSet<CoreEmailTemplate> CoreEmailTemplate { get; set; }
        public virtual DbSet<CoreFlag> CoreFlag { get; set; }
        public virtual DbSet<CoreLayoutLink> CoreLayoutLink { get; set; }
        public virtual DbSet<CoreLayoutUpdate> CoreLayoutUpdate { get; set; }
        public virtual DbSet<CoreResource> CoreResource { get; set; }
        public virtual DbSet<CoreSession> CoreSession { get; set; }
        public virtual DbSet<CoreStore> CoreStore { get; set; }
        public virtual DbSet<CoreStoreGroup> CoreStoreGroup { get; set; }
        public virtual DbSet<CoreTranslate> CoreTranslate { get; set; }
        public virtual DbSet<CoreUrlRewrite> CoreUrlRewrite { get; set; }
        public virtual DbSet<CoreVariable> CoreVariable { get; set; }
        public virtual DbSet<CoreVariableValue> CoreVariableValue { get; set; }
        public virtual DbSet<CoreWebsite> CoreWebsite { get; set; }
        public virtual DbSet<CouponAggregated> CouponAggregated { get; set; }
        public virtual DbSet<CouponAggregatedOrder> CouponAggregatedOrder { get; set; }
        public virtual DbSet<CouponAggregatedUpdated> CouponAggregatedUpdated { get; set; }
        public virtual DbSet<CronSchedule> CronSchedule { get; set; }
        public virtual DbSet<CustomerAddressEntity> CustomerAddressEntity { get; set; }
        public virtual DbSet<CustomerAddressEntityDatetime> CustomerAddressEntityDatetime { get; set; }
        public virtual DbSet<CustomerAddressEntityDecimal> CustomerAddressEntityDecimal { get; set; }
        public virtual DbSet<CustomerAddressEntityInt> CustomerAddressEntityInt { get; set; }
        public virtual DbSet<CustomerAddressEntityText> CustomerAddressEntityText { get; set; }
        public virtual DbSet<CustomerAddressEntityVarchar> CustomerAddressEntityVarchar { get; set; }
        public virtual DbSet<CustomerEavAttribute> CustomerEavAttribute { get; set; }
        public virtual DbSet<CustomerEavAttributeWebsite> CustomerEavAttributeWebsite { get; set; }
        public virtual DbSet<CustomerEntity> CustomerEntity { get; set; }
        public virtual DbSet<CustomerEntityDatetime> CustomerEntityDatetime { get; set; }
        public virtual DbSet<CustomerEntityDecimal> CustomerEntityDecimal { get; set; }
        public virtual DbSet<CustomerEntityInt> CustomerEntityInt { get; set; }
        public virtual DbSet<CustomerEntityText> CustomerEntityText { get; set; }
        public virtual DbSet<CustomerEntityVarchar> CustomerEntityVarchar { get; set; }
        public virtual DbSet<CustomerFormAttribute> CustomerFormAttribute { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroup { get; set; }
        public virtual DbSet<DataflowBatch> DataflowBatch { get; set; }
        public virtual DbSet<DataflowBatchExport> DataflowBatchExport { get; set; }
        public virtual DbSet<DataflowBatchImport> DataflowBatchImport { get; set; }
        public virtual DbSet<DataflowImportData> DataflowImportData { get; set; }
        public virtual DbSet<DataflowProfile> DataflowProfile { get; set; }
        public virtual DbSet<DataflowProfileHistory> DataflowProfileHistory { get; set; }
        public virtual DbSet<DataflowSession> DataflowSession { get; set; }
        public virtual DbSet<DesignChange> DesignChange { get; set; }
        public virtual DbSet<DirectoryCountry> DirectoryCountry { get; set; }
        public virtual DbSet<DirectoryCountryFormat> DirectoryCountryFormat { get; set; }
        public virtual DbSet<DirectoryCountryRegion> DirectoryCountryRegion { get; set; }
        public virtual DbSet<DirectoryCountryRegionName> DirectoryCountryRegionName { get; set; }
        public virtual DbSet<DirectoryCurrencyRate> DirectoryCurrencyRate { get; set; }
        public virtual DbSet<DownloadableLink> DownloadableLink { get; set; }
        public virtual DbSet<DownloadableLinkPrice> DownloadableLinkPrice { get; set; }
        public virtual DbSet<DownloadableLinkPurchased> DownloadableLinkPurchased { get; set; }
        public virtual DbSet<DownloadableLinkPurchasedItem> DownloadableLinkPurchasedItem { get; set; }
        public virtual DbSet<DownloadableLinkTitle> DownloadableLinkTitle { get; set; }
        public virtual DbSet<DownloadableSample> DownloadableSample { get; set; }
        public virtual DbSet<DownloadableSampleTitle> DownloadableSampleTitle { get; set; }
        public virtual DbSet<EavAttribute> EavAttribute { get; set; }
        public virtual DbSet<EavAttributeGroup> EavAttributeGroup { get; set; }
        public virtual DbSet<EavAttributeLabel> EavAttributeLabel { get; set; }
        public virtual DbSet<EavAttributeOption> EavAttributeOption { get; set; }
        public virtual DbSet<EavAttributeOptionValue> EavAttributeOptionValue { get; set; }
        public virtual DbSet<EavAttributeSet> EavAttributeSet { get; set; }
        public virtual DbSet<EavEntity> EavEntity { get; set; }
        public virtual DbSet<EavEntityAttribute> EavEntityAttribute { get; set; }
        public virtual DbSet<EavEntityDatetime> EavEntityDatetime { get; set; }
        public virtual DbSet<EavEntityDecimal> EavEntityDecimal { get; set; }
        public virtual DbSet<EavEntityInt> EavEntityInt { get; set; }
        public virtual DbSet<EavEntityStore> EavEntityStore { get; set; }
        public virtual DbSet<EavEntityText> EavEntityText { get; set; }
        public virtual DbSet<EavEntityType> EavEntityType { get; set; }
        public virtual DbSet<EavEntityVarchar> EavEntityVarchar { get; set; }
        public virtual DbSet<EavFormElement> EavFormElement { get; set; }
        public virtual DbSet<EavFormFieldset> EavFormFieldset { get; set; }
        public virtual DbSet<EavFormFieldsetLabel> EavFormFieldsetLabel { get; set; }
        public virtual DbSet<EavFormType> EavFormType { get; set; }
        public virtual DbSet<EavFormTypeEntity> EavFormTypeEntity { get; set; }
        public virtual DbSet<GiftcardOrder> GiftcardOrder { get; set; }
        public virtual DbSet<GiftcardsCard> GiftcardsCard { get; set; }
        public virtual DbSet<GiftcardsCardlist> GiftcardsCardlist { get; set; }
        public virtual DbSet<GiftcardsLog> GiftcardsLog { get; set; }
        public virtual DbSet<GiftcardsOrderItems> GiftcardsOrderItems { get; set; }
        public virtual DbSet<GiftcardsPregenerated> GiftcardsPregenerated { get; set; }
        public virtual DbSet<GiftcardTemplate> GiftcardTemplate { get; set; }
        public virtual DbSet<GiftMessage> GiftMessage { get; set; }
        public virtual DbSet<Giftvoucher> Giftvoucher { get; set; }
        public virtual DbSet<GiftvoucherCredit> GiftvoucherCredit { get; set; }
        public virtual DbSet<GiftvoucherCreditHistory> GiftvoucherCreditHistory { get; set; }
        public virtual DbSet<GiftvoucherCustomerVoucher> GiftvoucherCustomerVoucher { get; set; }
        public virtual DbSet<GiftvoucherHistory> GiftvoucherHistory { get; set; }
        public virtual DbSet<GiftvoucherProduct> GiftvoucherProduct { get; set; }
        public virtual DbSet<GiftvoucherTemplate> GiftvoucherTemplate { get; set; }
        public virtual DbSet<GooglecheckoutNotification> GooglecheckoutNotification { get; set; }
        public virtual DbSet<ImportexportImportdata> ImportexportImportdata { get; set; }
        public virtual DbSet<IndexEvent> IndexEvent { get; set; }
        public virtual DbSet<IndexProcess> IndexProcess { get; set; }
        public virtual DbSet<IndexProcessEvent> IndexProcessEvent { get; set; }
        public virtual DbSet<LogCustomer> LogCustomer { get; set; }
        public virtual DbSet<LogQuote> LogQuote { get; set; }
        public virtual DbSet<LogSummary> LogSummary { get; set; }
        public virtual DbSet<LogSummaryType> LogSummaryType { get; set; }
        public virtual DbSet<LogUrlInfo> LogUrlInfo { get; set; }
        public virtual DbSet<LogVisitor> LogVisitor { get; set; }
        public virtual DbSet<LogVisitorInfo> LogVisitorInfo { get; set; }
        public virtual DbSet<LogVisitorOnline> LogVisitorOnline { get; set; }
        public virtual DbSet<Magenotification> Magenotification { get; set; }
        public virtual DbSet<MagenotificationExtensionFeedback> MagenotificationExtensionFeedback { get; set; }
        public virtual DbSet<MagenotificationExtensionFeedbackmessage> MagenotificationExtensionFeedbackmessage { get; set; }
        public virtual DbSet<MagenotificationLicense> MagenotificationLicense { get; set; }
        public virtual DbSet<MagenotificationLog> MagenotificationLog { get; set; }
        public virtual DbSet<MailchimpErrors> MailchimpErrors { get; set; }
        public virtual DbSet<MailchimpSyncBatches> MailchimpSyncBatches { get; set; }
        public virtual DbSet<MFpcCrawlerloggedUrl> MFpcCrawlerloggedUrl { get; set; }
        public virtual DbSet<MFpcCrawlerUrl> MFpcCrawlerUrl { get; set; }
        public virtual DbSet<MFpcLog> MFpcLog { get; set; }
        public virtual DbSet<MFpcLogAggregated> MFpcLogAggregated { get; set; }
        public virtual DbSet<MFpcLogAggregatedDaily> MFpcLogAggregatedDaily { get; set; }
        public virtual DbSet<Mksstorelocator> Mksstorelocator { get; set; }
        public virtual DbSet<MMstcoreAttachment> MMstcoreAttachment { get; set; }
        public virtual DbSet<MMstcoreLogger> MMstcoreLogger { get; set; }
        public virtual DbSet<MMstcoreUrlrewrite> MMstcoreUrlrewrite { get; set; }
        public virtual DbSet<MRmaComment> MRmaComment { get; set; }
        public virtual DbSet<MRmaCondition> MRmaCondition { get; set; }
        public virtual DbSet<MRmaFedexLabel> MRmaFedexLabel { get; set; }
        public virtual DbSet<MRmaField> MRmaField { get; set; }
        public virtual DbSet<MRmaItem> MRmaItem { get; set; }
        public virtual DbSet<MRmaOfflineItem> MRmaOfflineItem { get; set; }
        public virtual DbSet<MRmaOfflineOrder> MRmaOfflineOrder { get; set; }
        public virtual DbSet<MRmaReason> MRmaReason { get; set; }
        public virtual DbSet<MRmaResolution> MRmaResolution { get; set; }
        public virtual DbSet<MRmaRma> MRmaRma { get; set; }
        public virtual DbSet<MRmaRmaCreditmemo> MRmaRmaCreditmemo { get; set; }
        public virtual DbSet<MRmaRmaOrder> MRmaRmaOrder { get; set; }
        public virtual DbSet<MRmaRmaStore> MRmaRmaStore { get; set; }
        public virtual DbSet<MRmaRule> MRmaRule { get; set; }
        public virtual DbSet<MRmaStatus> MRmaStatus { get; set; }
        public virtual DbSet<MRmaTemplate> MRmaTemplate { get; set; }
        public virtual DbSet<MRmaTemplateStore> MRmaTemplateStore { get; set; }
        public virtual DbSet<NewsletterProblem> NewsletterProblem { get; set; }
        public virtual DbSet<NewsletterQueue> NewsletterQueue { get; set; }
        public virtual DbSet<NewsletterQueueLink> NewsletterQueueLink { get; set; }
        public virtual DbSet<NewsletterQueueStoreLink> NewsletterQueueStoreLink { get; set; }
        public virtual DbSet<NewsletterSubscriber> NewsletterSubscriber { get; set; }
        public virtual DbSet<NewsletterTemplate> NewsletterTemplate { get; set; }
        public virtual DbSet<OauthConsumer> OauthConsumer { get; set; }
        public virtual DbSet<OauthNonce> OauthNonce { get; set; }
        public virtual DbSet<OauthToken> OauthToken { get; set; }
        public virtual DbSet<OnestepcheckoutConfigData> OnestepcheckoutConfigData { get; set; }
        public virtual DbSet<OnestepcheckoutDelivery> OnestepcheckoutDelivery { get; set; }
        public virtual DbSet<OnestepcheckoutSurvey> OnestepcheckoutSurvey { get; set; }
        public virtual DbSet<PaypalauthCustomer> PaypalauthCustomer { get; set; }
        public virtual DbSet<PaypalCert> PaypalCert { get; set; }
        public virtual DbSet<PaypalPaymentTransaction> PaypalPaymentTransaction { get; set; }
        public virtual DbSet<PaypalSettlementReport> PaypalSettlementReport { get; set; }
        public virtual DbSet<PaypalSettlementReportRow> PaypalSettlementReportRow { get; set; }
        public virtual DbSet<PermissionBlock> PermissionBlock { get; set; }
        public virtual DbSet<PermissionVariable> PermissionVariable { get; set; }
        public virtual DbSet<PersistentSession> PersistentSession { get; set; }
        public virtual DbSet<Poll> Poll { get; set; }
        public virtual DbSet<PollAnswer> PollAnswer { get; set; }
        public virtual DbSet<PollStore> PollStore { get; set; }
        public virtual DbSet<PollVote> PollVote { get; set; }
        public virtual DbSet<ProductAlertPrice> ProductAlertPrice { get; set; }
        public virtual DbSet<ProductAlertStock> ProductAlertStock { get; set; }
        public virtual DbSet<PromotionalgiftBanner> PromotionalgiftBanner { get; set; }
        public virtual DbSet<PromotionalgiftCatalogItem> PromotionalgiftCatalogItem { get; set; }
        public virtual DbSet<PromotionalgiftCatalogProduct> PromotionalgiftCatalogProduct { get; set; }
        public virtual DbSet<PromotionalgiftCatalogRule> PromotionalgiftCatalogRule { get; set; }
        public virtual DbSet<PromotionalgiftQuote> PromotionalgiftQuote { get; set; }
        public virtual DbSet<PromotionalgiftSale> PromotionalgiftSale { get; set; }
        public virtual DbSet<PromotionalgiftShoppingCartItem> PromotionalgiftShoppingCartItem { get; set; }
        public virtual DbSet<PromotionalgiftShoppingCartQuote> PromotionalgiftShoppingCartQuote { get; set; }
        public virtual DbSet<PromotionalgiftShoppingCartRule> PromotionalgiftShoppingCartRule { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<RatingEntity> RatingEntity { get; set; }
        public virtual DbSet<RatingOption> RatingOption { get; set; }
        public virtual DbSet<RatingOptionVote> RatingOptionVote { get; set; }
        public virtual DbSet<RatingOptionVoteAggregated> RatingOptionVoteAggregated { get; set; }
        public virtual DbSet<RatingStore> RatingStore { get; set; }
        public virtual DbSet<RatingTitle> RatingTitle { get; set; }
        public virtual DbSet<ReportComparedProductIndex> ReportComparedProductIndex { get; set; }
        public virtual DbSet<ReportEvent> ReportEvent { get; set; }
        public virtual DbSet<ReportEventTypes> ReportEventTypes { get; set; }
        public virtual DbSet<ReportViewedProductAggregatedDaily> ReportViewedProductAggregatedDaily { get; set; }
        public virtual DbSet<ReportViewedProductAggregatedMonthly> ReportViewedProductAggregatedMonthly { get; set; }
        public virtual DbSet<ReportViewedProductAggregatedYearly> ReportViewedProductAggregatedYearly { get; set; }
        public virtual DbSet<ReportViewedProductIndex> ReportViewedProductIndex { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<ReviewDetail> ReviewDetail { get; set; }
        public virtual DbSet<ReviewEntity> ReviewEntity { get; set; }
        public virtual DbSet<ReviewEntitySummary> ReviewEntitySummary { get; set; }
        public virtual DbSet<ReviewStatus> ReviewStatus { get; set; }
        public virtual DbSet<ReviewStore> ReviewStore { get; set; }
        public virtual DbSet<SalesBestsellersAggregatedDaily> SalesBestsellersAggregatedDaily { get; set; }
        public virtual DbSet<SalesBestsellersAggregatedMonthly> SalesBestsellersAggregatedMonthly { get; set; }
        public virtual DbSet<SalesBestsellersAggregatedYearly> SalesBestsellersAggregatedYearly { get; set; }
        public virtual DbSet<SalesBillingAgreement> SalesBillingAgreement { get; set; }
        public virtual DbSet<SalesBillingAgreementOrder> SalesBillingAgreementOrder { get; set; }
        public virtual DbSet<SalesFlatCreditmemo> SalesFlatCreditmemo { get; set; }
        public virtual DbSet<SalesFlatCreditmemoComment> SalesFlatCreditmemoComment { get; set; }
        public virtual DbSet<SalesFlatCreditmemoGrid> SalesFlatCreditmemoGrid { get; set; }
        public virtual DbSet<SalesFlatCreditmemoItem> SalesFlatCreditmemoItem { get; set; }
        public virtual DbSet<SalesFlatInvoice> SalesFlatInvoice { get; set; }
        public virtual DbSet<SalesFlatInvoiceComment> SalesFlatInvoiceComment { get; set; }
        public virtual DbSet<SalesFlatInvoiceGrid> SalesFlatInvoiceGrid { get; set; }
        public virtual DbSet<SalesFlatInvoiceItem> SalesFlatInvoiceItem { get; set; }
        public virtual DbSet<SalesFlatOrder> SalesFlatOrder { get; set; }
        public virtual DbSet<SalesFlatOrderAddress> SalesFlatOrderAddress { get; set; }
        public virtual DbSet<SalesFlatOrderGrid> SalesFlatOrderGrid { get; set; }
        public virtual DbSet<SalesFlatOrderItem> SalesFlatOrderItem { get; set; }
        public virtual DbSet<SalesFlatOrderPayment> SalesFlatOrderPayment { get; set; }
        public virtual DbSet<SalesFlatOrderStatusHistory> SalesFlatOrderStatusHistory { get; set; }
        public virtual DbSet<SalesFlatQuote> SalesFlatQuote { get; set; }
        public virtual DbSet<SalesFlatQuoteAddress> SalesFlatQuoteAddress { get; set; }
        public virtual DbSet<SalesFlatQuoteAddressItem> SalesFlatQuoteAddressItem { get; set; }
        public virtual DbSet<SalesFlatQuoteItem> SalesFlatQuoteItem { get; set; }
        public virtual DbSet<SalesFlatQuoteItemOption> SalesFlatQuoteItemOption { get; set; }
        public virtual DbSet<SalesFlatQuotePayment> SalesFlatQuotePayment { get; set; }
        public virtual DbSet<SalesFlatQuoteShippingRate> SalesFlatQuoteShippingRate { get; set; }
        public virtual DbSet<SalesFlatShipment> SalesFlatShipment { get; set; }
        public virtual DbSet<SalesFlatShipmentComment> SalesFlatShipmentComment { get; set; }
        public virtual DbSet<SalesFlatShipmentGrid> SalesFlatShipmentGrid { get; set; }
        public virtual DbSet<SalesFlatShipmentItem> SalesFlatShipmentItem { get; set; }
        public virtual DbSet<SalesFlatShipmentTrack> SalesFlatShipmentTrack { get; set; }
        public virtual DbSet<SalesInvoicedAggregated> SalesInvoicedAggregated { get; set; }
        public virtual DbSet<SalesInvoicedAggregatedOrder> SalesInvoicedAggregatedOrder { get; set; }
        public virtual DbSet<SalesOrderAggregatedCreated> SalesOrderAggregatedCreated { get; set; }
        public virtual DbSet<SalesOrderAggregatedUpdated> SalesOrderAggregatedUpdated { get; set; }
        public virtual DbSet<SalesOrderStatus> SalesOrderStatus { get; set; }
        public virtual DbSet<SalesOrderStatusLabel> SalesOrderStatusLabel { get; set; }
        public virtual DbSet<SalesOrderStatusState> SalesOrderStatusState { get; set; }
        public virtual DbSet<SalesOrderTax> SalesOrderTax { get; set; }
        public virtual DbSet<SalesOrderTaxItem> SalesOrderTaxItem { get; set; }
        public virtual DbSet<SalesPaymentTransaction> SalesPaymentTransaction { get; set; }
        public virtual DbSet<SalesRecurringProfile> SalesRecurringProfile { get; set; }
        public virtual DbSet<SalesRecurringProfileOrder> SalesRecurringProfileOrder { get; set; }
        public virtual DbSet<SalesRefundedAggregated> SalesRefundedAggregated { get; set; }
        public virtual DbSet<SalesRefundedAggregatedOrder> SalesRefundedAggregatedOrder { get; set; }
        public virtual DbSet<Salesrule> Salesrule { get; set; }
        public virtual DbSet<SalesruleCoupon> SalesruleCoupon { get; set; }
        public virtual DbSet<SalesruleCouponUsage> SalesruleCouponUsage { get; set; }
        public virtual DbSet<SalesruleCustomer> SalesruleCustomer { get; set; }
        public virtual DbSet<SalesruleCustomerGroup> SalesruleCustomerGroup { get; set; }
        public virtual DbSet<SalesruleLabel> SalesruleLabel { get; set; }
        public virtual DbSet<SalesruleProductAttribute> SalesruleProductAttribute { get; set; }
        public virtual DbSet<SalesruleWebsite> SalesruleWebsite { get; set; }
        public virtual DbSet<SalesShippingAggregated> SalesShippingAggregated { get; set; }
        public virtual DbSet<SalesShippingAggregatedOrder> SalesShippingAggregatedOrder { get; set; }
        public virtual DbSet<SendfriendLog> SendfriendLog { get; set; }
        public virtual DbSet<ShippingTablerate> ShippingTablerate { get; set; }
        public virtual DbSet<Sitemap> Sitemap { get; set; }
        public virtual DbSet<SpringbotActions> SpringbotActions { get; set; }
        public virtual DbSet<SpringbotCronCount> SpringbotCronCount { get; set; }
        public virtual DbSet<SpringbotCronQueue> SpringbotCronQueue { get; set; }
        public virtual DbSet<SpringbotRedirect> SpringbotRedirect { get; set; }
        public virtual DbSet<SpringbotRedirectOrder> SpringbotRedirectOrder { get; set; }
        public virtual DbSet<SpringbotTrackable> SpringbotTrackable { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagProperties> TagProperties { get; set; }
        public virtual DbSet<TagRelation> TagRelation { get; set; }
        public virtual DbSet<TagSummary> TagSummary { get; set; }
        public virtual DbSet<TaxCalculation> TaxCalculation { get; set; }
        public virtual DbSet<TaxCalculationRate> TaxCalculationRate { get; set; }
        public virtual DbSet<TaxCalculationRateTitle> TaxCalculationRateTitle { get; set; }
        public virtual DbSet<TaxCalculationRule> TaxCalculationRule { get; set; }
        public virtual DbSet<TaxClass> TaxClass { get; set; }
        public virtual DbSet<TaxOrderAggregatedCreated> TaxOrderAggregatedCreated { get; set; }
        public virtual DbSet<TaxOrderAggregatedUpdated> TaxOrderAggregatedUpdated { get; set; }
        public virtual DbSet<TinyCompressimagesImage> TinyCompressimagesImage { get; set; }
        public virtual DbSet<TinyCompressimagesTotals> TinyCompressimagesTotals { get; set; }
        public virtual DbSet<TmCacheLog> TmCacheLog { get; set; }
        public virtual DbSet<TmCoreModule> TmCoreModule { get; set; }
        public virtual DbSet<UltimateShipperMethod> UltimateShipperMethod { get; set; }
        public virtual DbSet<UsimplelicLicense> UsimplelicLicense { get; set; }
        public virtual DbSet<UsimpleupModule> UsimpleupModule { get; set; }
        public virtual DbSet<WeeeTax> WeeeTax { get; set; }
        public virtual DbSet<Widget> Widget { get; set; }
        public virtual DbSet<WidgetInstance> WidgetInstance { get; set; }
        public virtual DbSet<WidgetInstancePage> WidgetInstancePage { get; set; }
        public virtual DbSet<WidgetInstancePageLayout> WidgetInstancePageLayout { get; set; }
        public virtual DbSet<Wishlist> Wishlist { get; set; }
        public virtual DbSet<WishlistItem> WishlistItem { get; set; }
        public virtual DbSet<WishlistItemOption> WishlistItemOption { get; set; }
        public virtual DbSet<XmlconnectApplication> XmlconnectApplication { get; set; }
        public virtual DbSet<XmlconnectConfigData> XmlconnectConfigData { get; set; }
        public virtual DbSet<XmlconnectHistory> XmlconnectHistory { get; set; }
        public virtual DbSet<XmlconnectNotificationTemplate> XmlconnectNotificationTemplate { get; set; }
        public virtual DbSet<XmlconnectQueue> XmlconnectQueue { get; set; }
        public virtual DbSet<XtcoreConfigData> XtcoreConfigData { get; set; }
        public virtual DbSet<XtentoOrderexportDestination> XtentoOrderexportDestination { get; set; }
        public virtual DbSet<XtentoOrderexportLog> XtentoOrderexportLog { get; set; }
        public virtual DbSet<XtentoOrderexportProfile> XtentoOrderexportProfile { get; set; }
        public virtual DbSet<XtentoOrderexportProfileHistory> XtentoOrderexportProfileHistory { get; set; }
        public virtual DbSet<XtentoStockimportLog> XtentoStockimportLog { get; set; }
        public virtual DbSet<XtentoStockimportProfile> XtentoStockimportProfile { get; set; }
        public virtual DbSet<XtentoStockimportSource> XtentoStockimportSource { get; set; }
        public virtual DbSet<XtentoTrackingimportLog> XtentoTrackingimportLog { get; set; }
        public virtual DbSet<XtentoTrackingimportProfile> XtentoTrackingimportProfile { get; set; }
        public virtual DbSet<XtentoTrackingimportSource> XtentoTrackingimportSource { get; set; }
        public virtual DbSet<ZeonManufacturer> ZeonManufacturer { get; set; }
        public virtual DbSet<ZeonManufacturerStore> ZeonManufacturerStore { get; set; }

#endregion

        // Unable to generate entity type for table 'api_session'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_anc_categs_index_idx'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_anc_categs_index_tmp'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_anc_products_index_idx'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_anc_products_index_tmp'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_product_index_enbl_idx'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_product_index_enbl_tmp'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_product_index_idx'. Please see the warning messages.
        // Unable to generate entity type for table 'catalog_category_product_index_tmp'. Please see the warning messages.
        // Unable to generate entity type for table 'log_url'. Please see the warning messages.
        // Unable to generate entity type for table 'weee_discount'. Please see the warning messages.

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            ModelBuilderInit init = new ModelBuilderInit();
            init.OnModelCreating(modelBuilder);
        }
    }
}